### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by ntimo** [dcermak/vscode-rke-cluster-config#33]
Hello,
I would like to ask if it would be possible to also publish the extension to the Open VSK marketplace https://open-vsx.org/
This would allow users that don't or can't use the official MS marketplace install the extension.

best wishes,
Timo

**Comment by dcermak** [comment]
Sure, that can be done. I just need to get the namespace approved and then I'll push it there as well.

**Comment by dcermak** [comment]
It's available on open vsx now: https://open-vsx.org/extension/dancermak/vscode-rke-cluster-config
